### ISSUE TITLE
Update documentation for non-empty volumes

### ISSUE THREAD

**Issue by moklidia** [UffizziCloud/docs#62]
Update the Uffizzi compose file reference to include detail about using non-empty volumes

https://github.com/UffizziCloud/docs/blob/main/docs/references/compose-spec.md

**Comment by NealArw** [comment]
**TESTED - OK**

**Comment by NealArw** [comment]
**Tested - OK.**
Documentation https://github.com/UffizziCloud/docs/blob/main/docs/references/compose-spec.md was updated in main branch.
