### ISSUE TITLE
Create CLI documentation

### ISSUE THREAD

**Issue by moklidia** [UffizziCloud/docs#64]
Also, please note the update to the CLI documentation (i.e. on GitHub). We currently do not have a https://docs.uffizzi.com/cli page

**Comment by moklidia** [comment]
@gadkins What format should we use for CLI documentation? Can it be just the man format?

**Comment by moklidia** [comment]
For now, instead of creating a CLI documentation page, point users to the CLI repository

**Comment by gadkins** [comment]
For all `help` commands, change this URL to https://github.com/UffizziCloud/uffizzi_cli   

![Screen Shot 2022-08-08 at 11 24 12 AM](https://user-images.githubusercontent.com/7218230/183466254-baafc480-0a17-4a97-9b91-dbfe4795b11a.png)

**Comment by gadkins** [comment]
@moklidia @the38th  

See the preview deployment in this PR for the format to use when adding CLI documentation:   https://github.com/UffizziCloud/docs/pull/68
